name: oc-login Example
on: [ push, workflow_dispatch ]

jobs:
  login:
    name: OpenShift Login and Test
    runs-on: ubuntu-18.04
    env:
      TEST_MANIFEST: __tests__/manifests/timer.yaml
      TEST_USER: tetchell
      TEST_NAMESPACE: tetchell-dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in and set context
        uses: redhat-actions/oc-login@master
        with:
          openshift_server_url: ${{ secrets.TEST_OPENSHIFT_SERVER }}
          # openshift_token: ${{ secrets.TEST_OPENSHIFT_TOKEN }}
          openshift_username: ${{ env.TEST_USER }}
          openshift_password: ${{ secrets.TEST_OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true
          # certificate_authority_data: ${{ secrets.CA_DATA }}
          namespace: ${{ env.TEST_NAMESPACE }}

      - name: Deploy
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.TEST_NAMESPACE }}
          manifests: ${{ env.TEST_MANIFEST }}

      - name: Clean up
        run: |
          oc delete -f ${{ env.TEST_MANIFEST }}
