name: Multiplatform Workflow
on: [ workflow_dispatch ]

jobs:
  login:
    name: Multiplatform Workflow
    strategy:
      fail-fast: false
      max-parallel: 1   # this is just to prevent concurrent modification of my k8s cluster.
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    env:
      TEST_MANIFEST: __tests__/manifests/timer.yaml
      TEST_USER: tetchell
      TEST_NAMESPACE: tetchell-stage

    steps:
      - name: Install oc
        if: "runner.os != 'Linux'"
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: latest

      - name: Test oc
        run: oc version --client

      - name: Install kubectl
        if: "runner.os != 'Linux'"
        uses: azure/setup-kubectl@v1

      - name: Test kubectl
        run:
          kubectl version --client --short

      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@master
        with:
          openshift_server_url: ${{ secrets.TEST_OPENSHIFT_SERVER }}
          openshift_username: ${{ env.TEST_USER }}
          openshift_password: ${{ secrets.TEST_OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TEST_NAMESPACE }}

      - name: Deploy
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.TEST_NAMESPACE }}
          manifests: ${{ env.TEST_MANIFEST }}

      - name: Clean up
        run: |
          oc delete -f ${{ env.TEST_MANIFEST }}
