name: OpenShift Authentication Test Playground
on: [ push, workflow_dispatch ]

jobs:
  auth:
    name: OpenShift Login and Test
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate and set context
        id: auth
        uses: redhat-actions/oc-login@master
        with:
          openshift_server_url: ${{ secrets.TEST_OPENSHIFT_URL }}
          openshift_token: ${{ secrets.TEST_OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
